#!/usr/bin/env sh
set -eu

prefix="${PREFIX:-/usr}"
target_user="${UNEXUS_TARGET_USER:-}"

log() {
    printf '[uNexus provision] %s\n' "$*"
}

have() {
    command -v "$1" >/dev/null 2>&1
}

detect_target_user() {
    if [ -n "$target_user" ] && getent passwd "$target_user" >/dev/null 2>&1; then
        printf '%s\n' "$target_user"
        return 0
    fi

    if [ -n "${SUDO_USER:-}" ] && [ "$SUDO_USER" != "root" ] && getent passwd "$SUDO_USER" >/dev/null 2>&1; then
        printf '%s\n' "$SUDO_USER"
        return 0
    fi

    if [ -n "${PKEXEC_UID:-}" ]; then
        user_from_pkexec="$(getent passwd "$PKEXEC_UID" 2>/dev/null | cut -d: -f1 || true)"
        if [ -n "$user_from_pkexec" ]; then
            printf '%s\n' "$user_from_pkexec"
            return 0
        fi
    fi

    if have logname; then
        user_from_logname="$(logname 2>/dev/null || true)"
        if [ -n "$user_from_logname" ] && [ "$user_from_logname" != "root" ] && getent passwd "$user_from_logname" >/dev/null 2>&1; then
            printf '%s\n' "$user_from_logname"
            return 0
        fi
    fi

    return 1
}

run_as_user() {
    user="$1"
    shift

    if have runuser; then
        runuser -u "$user" -- "$@"
    elif have sudo; then
        sudo -u "$user" "$@"
    else
        "$@"
    fi
}

install_arch_packages() {
    if ! have pacman; then
        log "pacman not found; skipping package installation"
        return 0
    fi

    packages="flatpak gamemode mangohud xdg-desktop-portal xdg-desktop-portal-hyprland"
    missing=""
    for package in $packages; do
        if ! pacman -Q "$package" >/dev/null 2>&1; then
            missing="$missing $package"
        fi
    done

    if [ -n "$missing" ]; then
        log "installing packages:$missing"
        pacman -S --needed --noconfirm $missing
    else
        log "core gaming packages are already installed"
    fi
}

configure_user() {
    user="$1"
    groups="wheel audio video input storage gamemode"
    existing_groups=""

    for group_name in $groups; do
        if getent group "$group_name" >/dev/null 2>&1; then
            existing_groups="${existing_groups}${existing_groups:+,}${group_name}"
        fi
    done

    if [ -n "$existing_groups" ]; then
        log "adding $user to groups: $existing_groups"
        usermod -aG "$existing_groups" "$user" || true
    fi

    user_home="$(getent passwd "$user" | cut -d: -f6)"
    install -d -m 0755 -o "$user" -g "$user" "$user_home/.config/hypr"
    install -d -m 0755 -o "$user" -g "$user" "$user_home/.config/unexus"

    if [ ! -f "$user_home/.config/hypr/hyprland.conf" ]; then
        log "creating default Hyprland config for $user"
        cat > "$user_home/.config/hypr/hyprland.conf" <<'EOF'
# Generated by uNexus provisioner.
# The uNexus session wrapper sources this file before starting the shell.

monitor=,preferred,auto,1

input {
    kb_layout = us
    follow_mouse = 1
    touchpad {
        natural_scroll = true
    }
}

general {
    gaps_in = 4
    gaps_out = 8
    border_size = 2
    layout = dwindle
}

decoration {
    rounding = 8
    blur {
        enabled = true
        size = 5
        passes = 2
    }
}

animations {
    enabled = true
}

misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
    vfr = true
}
EOF
        chown "$user:$user" "$user_home/.config/hypr/hyprland.conf"
    else
        log "keeping existing Hyprland config for $user"
    fi
}

configure_flathub_and_launchers() {
    user="$1"

    if ! have flatpak; then
        log "flatpak not found; skipping Flathub and launcher setup"
        return 0
    fi

    log "configuring Flathub"
    flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo || true
    run_as_user "$user" flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo || true

    if [ "${UNEXUS_INSTALL_GAMING_LAUNCHERS:-1}" = "0" ]; then
        log "launcher installation disabled by UNEXUS_INSTALL_GAMING_LAUNCHERS=0"
        return 0
    fi

    launchers="com.valvesoftware.Steam net.lutris.Lutris com.heroicgameslauncher.hgl com.usebottles.bottles"
    for app_id in $launchers; do
        if run_as_user "$user" flatpak info --user "$app_id" >/dev/null 2>&1 || flatpak info "$app_id" >/dev/null 2>&1; then
            log "$app_id already installed"
            continue
        fi

        log "installing launcher $app_id for $user"
        run_as_user "$user" flatpak install --user -y flathub "$app_id" || log "could not install $app_id"
    done
}

configure_services() {
    if have systemctl; then
        log "enabling user and gaming services when available"
        systemctl enable NetworkManager.service >/dev/null 2>&1 || true
        systemctl enable systemd-timesyncd.service >/dev/null 2>&1 || true
    fi

    if have gamemoded; then
        log "GameMode daemon detected"
    else
        log "GameMode daemon not detected after package step"
    fi

    if have mangohud; then
        log "MangoHud detected"
    else
        log "MangoHud not detected after package step"
    fi
}

configure_bootloader() {
    if [ "${UNEXUS_CONFIGURE_BOOTLOADER:-1}" = "0" ]; then
        log "bootloader configuration disabled by UNEXUS_CONFIGURE_BOOTLOADER=0"
        return 0
    fi

    install -d -m 0755 /etc/unexus
    cat > /etc/unexus/bootloader.conf <<'EOF'
# uNexus boot defaults prepared by the installer.
kernel_options=quiet splash loglevel=3 rd.udev.log_level=3 vt.global_cursor_default=0
EOF

    if [ ! -d /boot/loader/entries ] || [ ! -f /boot/vmlinuz-linux ]; then
        log "systemd-boot layout not detected; wrote /etc/unexus/bootloader.conf only"
        return 0
    fi

    root_source="$(findmnt -no SOURCE / 2>/dev/null || true)"
    root_uuid=""
    if [ -n "$root_source" ] && have blkid; then
        root_uuid="$(blkid -s UUID -o value "$root_source" 2>/dev/null || true)"
    fi

    if [ -z "$root_uuid" ]; then
        log "root UUID not detected; skipping systemd-boot entry"
        return 0
    fi

    log "writing systemd-boot uNexus entry"
    {
        printf 'title   uNexus OS\n'
        printf 'linux   /vmlinuz-linux\n'
        [ -f /boot/intel-ucode.img ] && printf 'initrd  /intel-ucode.img\n'
        [ -f /boot/amd-ucode.img ] && printf 'initrd  /amd-ucode.img\n'
        printf 'initrd  /initramfs-linux.img\n'
        printf 'options root=UUID=%s rw quiet splash loglevel=3 rd.udev.log_level=3 vt.global_cursor_default=0\n' "$root_uuid"
    } > /boot/loader/entries/unexus-linux.conf
}

main() {
    if [ "$(id -u)" -ne 0 ]; then
        printf '[uNexus provision] must run as root.\n' >&2
        exit 1
    fi

    if ! target_user="$(detect_target_user)"; then
        printf '[uNexus provision] could not detect target user. Set UNEXUS_TARGET_USER.\n' >&2
        exit 1
    fi

    log "target user: $target_user"
    install_arch_packages
    configure_user "$target_user"
    configure_flathub_and_launchers "$target_user"
    configure_services
    configure_bootloader

    if [ -x "$prefix/bin/unexusctl" ]; then
        run_as_user "$target_user" "$prefix/bin/unexusctl" init >/dev/null 2>&1 || true
    fi

    log "done"
}

main "$@"
